# Generated by Django 3.2.9 on 2021-11-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='limit',
            field=models.IntegerField(default=0),
        ),
    ]
